### ISSUE TITLE
messssage should be message

### ISSUE THREAD

**Issue by bjonnh** [wsimmerson/autobot#1]
Trying your example I get in bot.read():
{'full': ':kornbluth.freenode.net NOTICE \* :**\* Looking up your hostname...\r\n', 'messsage': [':**_', 'Looking', 'up', 'your', 'hostname...'], 'nick': '_', 'source': ':kornbluth.freenode.net', 'command': 'NOTICE'}

Line 56 in **init**.py , messsage should be message.

**Comment by wsimmerson** [comment]
Fixed.
